name: Terraform Cloud Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Just notify
        run: echo "Code pushed - Terraform Cloud will handle deployment"
